### ISSUE TITLE
3.2.2.4.12 is a duplicate of 3.2.2.4.1 (until Aug 2018).

### ISSUE THREAD

**Issue by Santhanraj** [cabforum/documents#87] opened 2018-03-13 20:38 UTC
3.2.2.4.12 is a duplicate of 3.2.2.4.1 and will remain so until Aug 2018. Since BR expects the CAs to list the validation method used for each cert request, shouldn't this be fixed in the meantime so CAs are not listing them both (or is it acceptable to list either one)?

**Comment by timfromdigicert** [comment] 2018-03-13 22:07
Good question.  3.2.2.4.12 isn't actually a duplicate of 3.2.2.4.1 item (3); we made some improvements to it when we added it.

CAs should document which method they actually followed.  If they are following 3.2.2.4.1, they should document that, but if they are following 3.2.2.4.12 instead (which I would encourage), they can document that.

For the question behind your question, in the event that there are two validation methods that overlap, the CA should document which one they followed.  It's similar to if the same recipe was in two different cookbooks.  You just document which recipe you followed; the fact that you'd get the same results by following the other one isn't really relevant.

**Comment by Santhanraj** [comment] 2018-03-14 03:55
Appreciate the response, and apologies if I'm missing something obvious here, but how is 3.2.2.4.12 an improvement over 3.2.2.4.1 #3? Apart from "...directly with the Domain Name Registrar" being removed, they seems exactly the same to me.

_Confirming the Applicant's control over the FQDN by validating the Applicant is the Domain Contact directly with the Domain Name Registrar. This method may only be used if: 
The CA is also the Domain Name Registrar, or an Affiliate of the Registrar, of the Base Domain Name. 
Note: Once the FQDN has been validated using this method, the CA MAY also issue Certificates for other FQDNs that end with all the labels of the validated FQDN. This method is suitable for validating Wildcard Domain Names. For certificates issued on or after August 1, 2018, this method SHALL NOT be used for validation, and completed validations using this method SHALL NOT be used for the issuance of certificates. 

Confirming the Applicant's control over the FQDN by validating the Applicant is the Domain Contact. 
This method may only be used if the CA is also the Domain Name Registrar, or an Affiliate of the Registrar, of the Base Domain Name. 
Note: Once the FQDN has been validated using this method, the CA MAY also issue Certificates for other FQDNs that end with all the labels of the validated FQDN. This method is suitable for validating Wildcard Domain Names. _

**Comment by timfromdigicert** [comment] 2018-03-14 17:51
Hmm.  I thought we made some improvements and changes.  Maybe I'm remembering incorrectly.

**Closed** 2020-04-01 20:51 UTC
